export { default as About } from './about'
export { default as Navbar } from './navbar'
export { default as Footer } from './footer'
export { default as Greet } from './greetings'
export { default as Skills } from './skills'
export { default as Contact } from './contact'
export { default as Grid } from './grid'
